apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-application
  namespace: default
  labels:
    release: monitoring  # obrigatório: identifica este ServiceMonitor para o kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: cloud-application
  endpoints:
    - port: http
      path: /metrics
      interval: 30s